feat(CR pagination): DNS CR pagination and Cross Account params support
IBM/networking-go-sdk pull request #134
Opened 2023-04-20 02:16 UTC by gahlaut-rahul

## PR summary

**Fixes:** <! -- link to issue -->

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?  

## What is the new behavior?  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

**Summary**
1st. We have a customer demand where they want to create thousands of forwarding rule and need offset and limit to fetch these rules. As part of this sdk changes we are adding support to allow offset and limit for forwarding rules.

2nd. Cross Account list and name params are added, this commit has those changes as well.

2023-04-21 08:47 UTC, sandeep645 requested changes

2023-04-21 08:47 UTC, sandeep645 commented on dnssvcsv1/dns_svcs_v1_integration_test.go
> +	dnssvcsv1 "github.ibm.com/ibmcloud/networking-go-sdk/dnssvcsv1"
Could you point to public package instead of private ?

2023-04-21 08:48 UTC, sandeep645 commented
Update the PR with integration test results

2023-04-21 08:51 UTC, sandeep645 commented on dnssvcsv1/dns_svcs_v1_integration_test.go
> +		panic(err)
Should be panic(serviceErr) instead of panic(err)

2023-06-05 08:49 UTC, gahlaut-rahul commented
@sandeep645 : Snippet of test run.
<img width="1381" alt="image" src="https://github.com/IBM/networking-go-sdk/assets/104191096/1d571f19-edc6-4dd4-841b-010740640e7a">

2023-06-05 09:10 UTC, merged

2023-06-14 05:44 UTC, MalarvizhiK commented
:tada: This PR is included in version 0.41.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/networking-go-sdk/releases/tag/v0.41.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: