Adding Alwasy Online feature to Caching API
IBM/networking-go-sdk pull request #37
Opened 2021-02-22 07:47 UTC by shivaleelac

## PR summary

**Fixes:** <! -- link to issue -->

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?  

## What is the new behavior?  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2021-02-22 15:34 UTC, KumarGanesanIBM commented
@nimisha0092 
looks like, there was an intermittent error in Page Rule IT. It passed now.
can you please add the ssl certificate skip statement (which we did in internal repo) as part of this PR..?
Thanks,

2021-02-23 07:25 UTC, KumarGanesanIBM approved these changes
Looks good to me.

2021-02-23 14:51 UTC, kennburger requested changes

2021-02-23 14:51 UTC, kennburger commented on cachingapiv1/caching_api_v1.go
> + * (C) Copyright IBM Corp. 2021.
If this was originally released in 2020, It should read '2020, 2021'.

2021-02-23 14:51 UTC, kennburger commented on cachingapiv1/caching_api_v1_suite_test.go
> + * (C) Copyright IBM Corp. 2021.
Same comment here ...  2020, 2021

2021-02-23 14:51 UTC, kennburger commented on cachingapiv1/caching_api_v1_test.go
> + * (C) Copyright IBM Corp. 2021.
2020, 2021

2021-02-23 17:49 UTC, kennburger approved these changes
LGTM

2021-02-23 18:26 UTC, ajay-malhotra1 approved these changes
lgtm

2021-02-26 14:14 UTC, merged

2021-02-26 15:45 UTC, ajay-malhotra1 commented
:tada: This PR is included in version 0.13.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/networking-go-sdk/releases/tag/v0.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: