CIS SDK for filters and Firewall rules
IBM/networking-go-sdk pull request #41
Opened 2021-04-08 13:53 UTC by DwitikrDash

## PR summary

**Fixes:** <! -- link to issue -->

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?  

## What is the new behavior?  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2021-04-08 15:00 UTC, kennburger requested changes

2021-04-12 10:47 UTC, DwitikrDash commented on filtersv1/filters_v1_integration_test.go
> + * (C) Copyright IBM Corp. 2020.
Updated to 2021

2021-04-12 10:47 UTC, DwitikrDash commented on firewallrulesv1/firewall_rules_v1_integration_test.go
> + * (C) Copyright IBM Corp. 2020.
Updated to 2021

2021-04-12 10:47 UTC, DwitikrDash commented on sslcertificateapiv1/ssl_certificate_api_v1_integration_test.go
> +				Expect(*orderResult.Result.Type).Should(BeEquivalentTo("advanced"))
Updated to 2021

2021-04-14 05:33 UTC, csulrong approved these changes

2021-04-15 09:39 UTC, MalarvizhiK approved these changes
LGTM

2021-04-15 15:17 UTC, kennburger approved these changes

2021-04-15 16:01 UTC, merged

2021-04-29 21:28 UTC, ajay-malhotra1 commented
:tada: This PR is included in version 0.14.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/networking-go-sdk/releases/tag/v0.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: